### ISSUE TITLE
Import fails on Python 3.10.0b1

### ISSUE THREAD

**Issue by mattclay** [jborean93/pyspnego#10]
```
Python 3.10.0b1 (default, May  6 2021, 02:44:57) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spnego
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/demo/lib/python3.10/site-packages/spnego/__init__.py", line 12, in <module>
    from spnego._context import (
  File "/tmp/demo/lib/python3.10/site-packages/spnego/_context.py", line 37, in <module>
    from spnego.iov import (
  File "/tmp/demo/lib/python3.10/site-packages/spnego/iov.py", line 14, in <module>
    class BufferType(IntFlag):
  File "/usr/lib/python3.10/enum.py", line 544, in __new__
    raise TypeError(
TypeError: invalid Flag 'BufferType' -- missing values: 4, 8
```

This appears to be due to this change in CPython: https://github.com/python/cpython/pull/24215

**Comment by jborean93** [comment]
Hmm I saw this when trying out the alpha and I hoped it would not be the case on the beta but obviously not. This personally seems like a breaking change on their part and I cannot understand the reasons why this is not required. I’ll have to try and follow it up.

**Comment by jborean93** [comment]
So I was wrong, I was mistakenly using `IntFlag` instead of `IntEnum` here causing the problems. The field is a single value so shouldn't be `IntFlag` and is the reason why it's complaining that 4 and 8 were missing.
