### ISSUE TITLE
Kerberos incomplete context error during auth

### ISSUE THREAD

**Issue by baloncu** [jborean93/pyspnego#55]
I am trying to use pypsrp to send remote commands to my windows machine which only accepts kerberos authentication. 
When I try the following code snippet, it complains about the shellID. I assumed shell Id would be randomly assigned and not something user has to provide. 
Just to note that I can do winrs using powershell from another windows machine to this target (windows machine), and it works okay.

```
PS C:\Users\mozsoy> python3.10.exe
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypsrp.wsman import WSMan
>>> from pypsrp.shell import Process, SignalCode, WinRS
>>> wsman=WSMan("<hostname>", auth="kerberos", username="MOzsoy", ssl=False)
>>> winrs_shell = WinRS(wsman)
>>> proc = Process(winrs_shell, "dir")
>>> proc.invoke()
Traceback (most recent call last):
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\wsman.py", line 855, in _send_request
    response.raise_for_status()
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: <hostname>:5985/wsman

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\wsman.py", line 470, in invoke
    response = self.transport.send(xml)
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\wsman.py", line 837, in send
    return self._send_request(prep_request)
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\wsman.py", line 862, in _send_request
    raise WinRMTransportError("http", code, response_text)
pypsrp.exceptions.WinRMTransportError: Bad HTTP response returned from the server. Code: 500, Content: '<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.dmtf.org/wbem/wsman/1/wsman/fault</a:Action><a:MessageID>uuid:22E8A494-DE50-4A03-8122-AB8DFEFCD689</a:MessageID><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:2B09A45A-DB37-4207-A9DB-57DDBEDAE8AF</a:RelatesTo></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value>w:InvalidSelectors</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">The WS-Management service cannot process the request because the request did not contain all required selectors. </s:Text></s:Reason><s:Detail><w:FaultDetail>http://schemas.dmtf.org/wbem/wsman/1/wsman/faultDetail/InsufficientSelectors</w:FaultDetail><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858842" Machine="2nnrcs2.corp.intusurg.com"><f:Message>The Windows Remote Shell cannot process the request because it requires the following selector: ShellId. Retry with the correct selector.  </f:Message></f:WSManFault></s:Detail></s:Fault></s:Body></s:Envelope>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\shell.py", line 399, in invoke
    self.begin_invoke()
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\shell.py", line 384, in begin_invoke
    response = self.shell.command(self.executable, self.arguments, no_shell=self.no_shell)
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\shell.py", line 151, in command
    return self.wsman.command(self.resource_uri, cmd, option_set=options, selector_set=self._selector_set)
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\wsman.py", line 268, in command
    res = self.invoke(WSManAction.COMMAND, resource_uri, resource, option_set, selector_set, timeout)
  File "C:\Users\mozsoy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pypsrp\wsman.py", line 474, in invoke
    raise self._parse_wsman_fault(err.response_text)
pypsrp.exceptions.WSManFaultError: Received a WSManFault message. (Code: 2150858842, Machine: <hostname>, Reason: The Windows Remote Shell cannot process the request because it requires the following selector: ShellId. Retry with the correct selector.)
```

same code snippet on linux side gives me an error "No context has been established". 

```
Python 3.7.10 (default, Feb 20 2021, 21:21:24)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypsrp.shell import Process, SignalCode, WinRS
>>> from pypsrp.wsman import WSMan
>>> wsman = WSMan('<hostname>', auth='kerberos', ssl=False, username='MOzsoy')
>>> winrs_shell = WinRS(wsman)
>>> proc = Process(winrs_shell, "dir")
>>> proc.invoke()
Traceback (most recent call last):
  File "/home/mozsoy/.local/lib/python3.7/site-packages/spnego/_context.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/spnego/_gss.py", line 552, in step
    self._context_attr = int(self._context.actual_flags)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/gssapi/_utils.py", line 61, in inquire_property
    return getattr(self._inquire(**{name: True}), name)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/gssapi/sec_contexts.py", line 455, in _inquire
    res = rsec_contexts.inquire_context(self, **kwargs)
  File "gssapi/raw/sec_contexts.pyx", line 363, in gssapi.raw.sec_contexts.inquire_context
gssapi.raw.exceptions.MissingContextError: Major (524288): No context has been established, Minor (39756039): Attempt to use incomplete security context

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/shell.py", line 399, in invoke
    self.begin_invoke()
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/shell.py", line 384, in begin_invoke
    response = self.shell.command(self.executable, self.arguments, no_shell=self.no_shell)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/shell.py", line 151, in command
    return self.wsman.command(self.resource_uri, cmd, option_set=options, selector_set=self._selector_set)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 268, in command
    res = self.invoke(WSManAction.COMMAND, resource_uri, resource, option_set, selector_set, timeout)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 470, in invoke
    response = self.transport.send(xml)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 803, in send
    self._send_request(prep_request)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 840, in _send_request
    response = self.session.send(request, timeout=(self.connection_timeout, self.read_timeout))  # type: ignore[union-attr] # This should not happen
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 594, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/negotiate.py", line 96, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/negotiate.py", line 141, in handle_401
    out_token = context.step()
  File "/home/mozsoy/.local/lib/python3.7/site-packages/spnego/_context.py", line 70, in wrapper
    raise SpnegoError(base_error=native_err, context_msg=context) from native_err
spnego.exceptions.NoContextError: SpnegoError (8): Major (524288): No context has been established, Minor (39756039): Attempt to use incomplete security context, Context: Processing security token
```

Finally I wanted to test `psrp` only but that module is not found.
```
Python 3.7.10 (default, Feb 20 2021, 21:21:24)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psrp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'psrp'
```

**Comment by baloncu** [comment]
Thanks for merging the fix, I will test and report. In the meantime, I tried to move my kerberos version to 1.20. It seemed like a successful upgrade but now I get a connection error. Maybe some settings got messed up. 

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='2nnrcs2.corp.intusurg.com', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa26bcd8d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by jborean93** [comment]
That's a DNS problem, the host is unable to resolve `2nnrcs2.corp.intusurg.com`.

**Comment by baloncu** [comment]
The previous one seems like a DNS issue, you are right. I just retried it. I still get the security context related error. Even though seems like my kerberos version is 1.20

```
(host) mozsoy@mozsoy-ud1:~/orion2/run$ klist -V
Kerberos 5 version 1.20
```

```
(host) mozsoy@mozsoy-ud1:~/orion2/run$ python3.7
Python 3.7.10 (default, Feb 20 2021, 21:21:24)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypsrp.shell import Process, WinRS
>>> from pypsrp.wsman import WSMan
>>> wsman=WSMan("2nnrcs2.corp.intusurg.com", auth="kerberos", username="MOzsoy", ssl=False)
>>> with wsman, WinRS(wsman) as shell:
...     process = Process(shell,"dir")
...     process.invoke()
...
[121266] 1667521295.549561: Retrieving MOzsoy@CORP.INTUSURG.COM from FILE:/etc/krb5/user/365090202/client.keytab (vno 0, enctype 0) with result: 2/Key table file '/etc/krb5/user/365090202/client.keytab' not found
[121266] 1667521295.569388: Getting credentials MOzsoy@CORP.INTUSURG.COM -> WSMAN/2nnrcs2.corp.intusurg.com@CORP.INTUSURG.COM using ccache FILE:/tmp/krb5cc_cdc365090202_Z7xTcY
[121266] 1667521295.569441: Retrieving MOzsoy@CORP.INTUSURG.COM -> WSMAN/2nnrcs2.corp.intusurg.com@CORP.INTUSURG.COM from FILE:/tmp/krb5cc_cdc365090202_Z7xTcY with result: -1765328243/Matching credential not found
[121266] 1667521295.569479: Retrieving MOzsoy@CORP.INTUSURG.COM -> krbtgt/CORP.INTUSURG.COM@CORP.INTUSURG.COM from FILE:/tmp/krb5cc_cdc365090202_Z7xTcY with result: 0/Success
[121266] 1667521295.569487: Starting with TGT for client realm: MOzsoy@CORP.INTUSURG.COM -> krbtgt/CORP.INTUSURG.COM@CORP.INTUSURG.COM
[121266] 1667521295.569493: Requesting tickets for WSMAN/2nnrcs2.corp.intusurg.com@CORP.INTUSURG.COM, referrals on
[121266] 1667521295.569509: Generated subkey for TGS request: aes256-cts/B1CE
[121266] 1667521295.569538: etypes requested in TGS request: aes256-cts, aes128-cts, rc4-hmac, des, des-cbc-crc
[121266] 1667521295.569597: Encoding request body and padata into FAST request
[121266] 1667521295.569655: Sending request (3821 bytes) to CORP.INTUSURG.COM
[121266] 1667521295.569671: Resolving hostname hq-dc1.corp.intusurg.com
[121266] 1667521295.578717: Initiating TCP connection to stream 172.20.250.95:88
[121266] 1667521295.579410: Sending TCP request to stream 172.20.250.95:88
[121266] 1667521295.598005: Received answer (3797 bytes) from stream 172.20.250.95:88
[121266] 1667521295.598020: Terminating TCP connection to stream 172.20.250.95:88
[121266] 1667521295.598057: Response was from master KDC
[121266] 1667521295.598072: Decoding FAST response
[121266] 1667521295.598149: FAST reply key: aes256-cts/1FD0
[121266] 1667521295.598177: TGS reply is for MOzsoy@CORP.INTUSURG.COM -> WSMAN/2nnrcs2.corp.intusurg.com@CORP.INTUSURG.COM with session key aes256-cts/A208
[121266] 1667521295.598197: TGS request result: 0/Success
[121266] 1667521295.598202: Received creds for desired service WSMAN/2nnrcs2.corp.intusurg.com@CORP.INTUSURG.COM
[121266] 1667521295.598209: Storing MOzsoy@CORP.INTUSURG.COM -> WSMAN/2nnrcs2.corp.intusurg.com@CORP.INTUSURG.COM in FILE:/tmp/krb5cc_cdc365090202_Z7xTcY
[121266] 1667521295.598569: Creating authenticator for MOzsoy@CORP.INTUSURG.COM -> WSMAN/2nnrcs2.corp.intusurg.com@CORP.INTUSURG.COM, seqnum 183743689, subkey aes256-cts/1D65, session key aes256-cts/A208
Traceback (most recent call last):
  File "/home/mozsoy/.local/lib/python3.7/site-packages/spnego/_context.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/spnego/_gss.py", line 552, in step
    self._context_attr = int(self._context.actual_flags)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/gssapi/_utils.py", line 61, in inquire_property
    return getattr(self._inquire(**{name: True}), name)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/gssapi/sec_contexts.py", line 455, in _inquire
    res = rsec_contexts.inquire_context(self, **kwargs)
  File "gssapi/raw/sec_contexts.pyx", line 363, in gssapi.raw.sec_contexts.inquire_context
gssapi.raw.exceptions.MissingContextError: Major (524288): No context has been established, Minor (39756039): Attempt to use incomplete security context

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/shell.py", line 96, in __enter__
    self.open()
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/shell.py", line 205, in open
    response = self.wsman.create(self.resource_uri, shell, option_set=options if len(options.values) else None)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 290, in create
    res = self.invoke(WSManAction.CREATE, resource_uri, resource, option_set, selector_set, timeout)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 470, in invoke
    response = self.transport.send(xml)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 803, in send
    self._send_request(prep_request)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/wsman.py", line 840, in _send_request
    response = self.session.send(request, timeout=(self.connection_timeout, self.read_timeout))  # type: ignore[union-attr] # This should not happen
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 594, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/negotiate.py", line 96, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/home/mozsoy/.local/lib/python3.7/site-packages/pypsrp/negotiate.py", line 141, in handle_401
    out_token = context.step()
  File "/home/mozsoy/.local/lib/python3.7/site-packages/spnego/_context.py", line 70, in wrapper
    raise SpnegoError(base_error=native_err, context_msg=context) from native_err
spnego.exceptions.NoContextError: SpnegoError (8): Major (524288): No context has been established, Minor (39756039): Attempt to use incomplete security context, Context: Processing security token
```

**Comment by jborean93** [comment]
The new version of pyspnego just went out (minutes ago). Make sure that you have 0.6.3 installed.

**Comment by baloncu** [comment]
okay, I went a little overboard and uninstalled couple more modules, rebooted my machine and installed them again. It works now with kerberos 1.20.
Thank you very much for all the help.
