### ISSUE TITLE
Kerberos incorrect real_name for krbtgt

### ISSUE THREAD

**Issue by sangetang** [jborean93/pyspnego#74]
![image](https://github.com/jborean93/pyspnego/assets/75775441/4f8f78ec-7478-4b33-bb06-78a07698c516)

Traceback (most recent call last):
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/requests_kerberos/kerberos_.py", line 227, in generate_request_header
    gss_response = ctx.step(in_token=negotiate_resp_value)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/spnego/_context.py", line 71, in wrapper
    raise SpnegoError(base_error=native_err, context_msg=context) from native_err
spnego.exceptions.SpnegoError: SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server krbtgt/EC2.INTERNAL@US.COTTICOFFEE.GLOBAL not found in Kerberos database, Context: Processing security token
2023-12-11 06:34:44,812:ERROR:requests_kerberos.kerberos_:SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server krbtgt/EC2.INTERNAL@US.COTTICOFFEE.GLOBAL not found in Kerberos database, Context: Processing security token
Traceback (most recent call last):
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/spnego/_context.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/spnego/_gss.py", line 431, in step
    out_token = self._context.step(in_token)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/gssapi/_utils.py", line 165, in check_last_err
    return func(self, *args, **kwargs)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/gssapi/_utils.py", line 131, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/gssapi/sec_contexts.py", line 584, in step
    return self._initiator_step(token=token)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/gssapi/sec_contexts.py", line 606, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 188, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server krbtgt/EC2.INTERNAL@US.COTTICOFFEE.GLOBAL not found in Kerberos database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/requests_kerberos/kerberos_.py", line 227, in generate_request_header
    gss_response = ctx.step(in_token=negotiate_resp_value)
  File "/home/miniconda3/envs/superset/lib/python3.9/site-packages/spnego/_context.py", line 71, in wrapper
    raise SpnegoError(base_error=native_err, context_msg=context) from native_err
spnego.exceptions.SpnegoError: SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server krbtgt/EC2.INTERNAL@US.COTTICOFFEE.GLOBAL not found in Kerberos database, Context: Processing security token

**Comment by sangetang** [comment]
I do not know why the realName changed to "EC2.INTERNAL"

**Comment by sangetang** [comment]
1
